### ISSUE TITLE
Won't Connect

### ISSUE THREAD

**Issue by Bra1nK** [dc297/mqttclpro#1] opened 2016-12-09 13:40 UTC
Fails to connect to my broker. The standalone MQTT Client app works OK but not this Tasker plugin

**Comment by dc297** [comment] 2016-12-09 14:47
Please try giving storage permission to the app.

**Comment by Bra1nK** [comment] 2016-12-09 14:53
Did that already but just reinstalled and tried again but still no joy, just sits there saying "Connecting..."

**Comment by dc297** [comment] 2016-12-09 14:55
can share logcat?

**Comment by Bra1nK** [comment] 2016-12-09 15:00
How do I do that ?

**Comment by dc297** [comment] 2016-12-09 15:07
try the following link : http://forum.xda-developers.com/showthread.php?t=1726238 . Let me know if you need more help.

**Comment by Bra1nK** [comment] 2016-12-09 15:21
--------- beginning of main
D/RelationGraph(18401): garbageCollect()
D/AbsListView(18401): Get MotionRecognitionManager
E/MotionRecognitionManager(18401): mSContextService = android.hardware.scontext.ISContextService$Stub$Proxy@cba3162
E/MotionRecognitionManager(18401): motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@a1f12f3
E/MotionRecognitionManager(18401): motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@a1f12f3
D/Activity(18401): performCreate Call Injection manager
I/InjectionManager(18401): dispatchOnViewCreated > Target : org.jtb.alogcat.LogActivity isFragment :false
D/ViewRootImpl(18401): #1 mView = com.android.internal.policy.PhoneWindow$DecorView{b9d1fe5 I.E...... R.....ID 0,0-0,0}
D/ViewRootImpl(18401): #1 mView = android.widget.LinearLayout{1bc8aba V.E...... ......I. 0,0-0,0}
I/InjectionManager(18401): dispatchCreateOptionsMenu :org.jtb.alogcat.LogActivity
I/InjectionManager(18401): dispatchPrepareOptionsMenu :org.jtb.alogcat.LogActivity
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
I/Timeline(18401): Timeline: Activity_idle id: android.os.BinderProxy@fc70a29 time:1668217
D/ViewRootImpl(18401): #3 mView = null
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
I/InjectionManager(18401): dispatchPrepareOptionsMenu :org.jtb.alogcat.LogActivity
D/AbsListView(18401): Get MotionRecognitionManager
D/ViewRootImpl(18401): #1 mView = android.widget.PopupWindow$PopupDecorView{22787e9 V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
I/InjectionManager(18401): dispatchOptionsItemSelected :org.jtb.alogcat.LogActivity
D/ViewRootImpl(18401): #3 mView = null
W/InputEventReceiver(18401): Attempted to finish an input event but the input event receiver has already been disposed.
D/ViewRootImpl(18401): #1 mView = android.widget.LinearLayout{dbd071b V.E...... ......I. 0,0-0,0}
E/ViewRootImpl(18401): sendUserActionEvent() mView == null
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl(18401): #3 mView = null
D/ViewRootImpl(18401): ViewPostImeInputStage processKey 0
D/ViewRootImpl(18401): ViewPostImeInputStage processKey 1
D/ViewRootImpl(18401): #3 mView = null
D/RelationGraph(18401): garbageCollect()
--------- beginning of system
W/ResourcesManager(18401): getTopLevelResources: /data/app/org.jtb.alogcat-1/base.apk / 1.0 running in org.jtb.alogcat rsrc of package org.jtb.alogcat
D/AbsListView(18401): Get MotionRecognitionManager
E/MotionRecognitionManager(18401): mSContextService = android.hardware.scontext.ISContextService$Stub$Proxy@3fc5971
E/MotionRecognitionManager(18401): motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@418b356
E/MotionRecognitionManager(18401): motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@418b356
D/Activity(18401): performCreate Call Injection manager
I/InjectionManager(18401): dispatchOnViewCreated > Target : org.jtb.alogcat.LogActivity isFragment :false
D/ViewRootImpl(18401): #1 mView = com.android.internal.policy.PhoneWindow$DecorView{2ffc530 I.E...... R.....ID 0,0-0,0}
D/SecWifiDisplayUtil(18401): Metadata value : SecSettings2
D/ViewRootImpl(18401): #1 mView = android.widget.LinearLayout{81bc5a9 V.E...... ......I. 0,0-0,0}
I/InjectionManager(18401): dispatchCreateOptionsMenu :org.jtb.alogcat.LogActivity
I/InjectionManager(18401): dispatchPrepareOptionsMenu :org.jtb.alogcat.LogActivity
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
I/Timeline(18401): Timeline: Activity_idle id: android.os.BinderProxy@64b60c4 time:1864091
D/ViewRootImpl(18401): #3 mView = null
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
I/InjectionManager(18401): dispatchPrepareOptionsMenu :org.jtb.alogcat.LogActivity
D/AbsListView(18401): Get MotionRecognitionManager
D/ViewRootImpl(18401): #1 mView = android.widget.PopupWindow$PopupDecorView{2317184 V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
I/InjectionManager(18401): dispatchOptionsItemSelected :org.jtb.alogcat.LogActivity
I/Timeline(18401): Timeline: Activity_launch_request id:org.jtb.alogcat time:1871471
D/ViewRootImpl(18401): #3 mView = null
W/InputEventReceiver(18401): Attempted to finish an input event but the input event receiver has already been disposed.
E/ViewRootImpl(18401): sendUserActionEvent() mView == null
D/RelationGraph(18401): garbageCollect()
W/ResourcesManager(18401): getTopLevelResources: /data/app/org.jtb.alogcat-1/base.apk / 1.0 running in org.jtb.alogcat rsrc of package org.jtb.alogcat
W/ResourcesManager(18401): getTopLevelResources: /data/app/org.jtb.alogcat-1/base.apk / 1.0 running in org.jtb.alogcat rsrc of package org.jtb.alogcat
D/AbsListView(18401): Get MotionRecognitionManager
E/MotionRecognitionManager(18401): mSContextService = android.hardware.scontext.ISContextService$Stub$Proxy@cd4b177
E/MotionRecognitionManager(18401): motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@dac01e4
E/MotionRecognitionManager(18401): motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@dac01e4
I/InjectionManager(18401): dispatchBuildHeader > Target : org.jtb.alogcat.PrefsActivity
D/AbsListView(18401): Get MotionRecognitionManager
D/Activity(18401): performCreate Call Injection manager
I/InjectionManager(18401): dispatchPreferences > Target : org.jtb.alogcat.PrefsActivity
I/InjectionManager(18401): dispatchOnViewCreated > Target : org.jtb.alogcat.PrefsActivity isFragment :false
D/ViewRootImpl(18401): #1 mView = com.android.internal.policy.PhoneWindow$DecorView{5f0d981 I.E...... R.....ID 0,0-0,0}
D/SecWifiDisplayUtil(18401): Metadata value : SecSettings2
W/System.err(18401): remove failed: ENOENT (No such file or directory) : /data/user/0/org.jtb.alogcat/shared_prefs/org.jtb.alogcat_preferences.xml.bak
I/InjectionManager(18401): dispatchCreateOptionsMenu :org.jtb.alogcat.PrefsActivity
I/InjectionManager(18401): dispatchPrepareOptionsMenu :org.jtb.alogcat.PrefsActivity
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
I/Timeline(18401): Timeline: Activity_idle id: android.os.BinderProxy@9db2205 time:1871675
V/ActivityThread(18401): updateVisibility : ActivityRecord{6a240ed token=android.os.BinderProxy@64b60c4 {org.jtb.alogcat/org.jtb.alogcat.LogActivity}} show : false
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(18401): ViewPostImeInputStage processKey 0
D/ViewRootImpl(18401): ViewPostImeInputStage processKey 1
D/ViewRootImpl(18401): #1 mView = android.widget.LinearLayout{3231b70 V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
I/Timeline(18401): Timeline: Activity_idle id: android.os.BinderProxy@64b60c4 time:1880394
D/ViewRootImpl(18401): #3 mView = null
D/ViewRootImpl(18401): #3 mView = null
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
I/InjectionManager(18401): dispatchPrepareOptionsMenu :org.jtb.alogcat.LogActivity
D/AbsListView(18401): Get MotionRecognitionManager
D/ViewRootImpl(18401): #1 mView = android.widget.PopupWindow$PopupDecorView{30a7fef V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
I/InjectionManager(18401): dispatchOptionsItemSelected :org.jtb.alogcat.LogActivity
D/ViewRootImpl(18401): #3 mView = null
W/InputEventReceiver(18401): Attempted to finish an input event but the input event receiver has already been disposed.
D/ViewRootImpl(18401): #1 mView = android.widget.LinearLayout{b0aaed7 V.E...... ......I. 0,0-0,0}
E/ViewRootImpl(18401): sendUserActionEvent() mView == null
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl(18401): #3 mView = null
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
I/InjectionManager(18401): dispatchPrepareOptionsMenu :org.jtb.alogcat.LogActivity
D/AbsListView(18401): Get MotionRecognitionManager
D/ViewRootImpl(18401): #1 mView = android.widget.PopupWindow$PopupDecorView{c15822e V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1

**Comment by Bra1nK** [comment] 2016-12-09 15:22
Does that help ?

**Comment by dc297** [comment] 2016-12-09 15:29
not really. Can you launch the app and share the logcat of that time. That would be of great help.

**Comment by Bra1nK** [comment] 2016-12-09 15:36
--------- beginning of main
D/RelationGraph(18401): garbageCollect()
D/AbsListView(18401): Get MotionRecognitionManager
E/MotionRecognitionManager(18401): mSContextService = android.hardware.scontext.ISContextService$Stub$Proxy@218d523
E/MotionRecognitionManager(18401): motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@1959a20
E/MotionRecognitionManager(18401): motionService = com.samsung.android.motion.IMotionRecognitionService$Stub$Proxy@1959a20
D/Activity(18401): performCreate Call Injection manager
I/InjectionManager(18401): dispatchOnViewCreated > Target : org.jtb.alogcat.LogActivity isFragment :false
D/ViewRootImpl(18401): #1 mView = com.android.internal.policy.PhoneWindow$DecorView{782e5aa I.E...... R.....ID 0,0-0,0}
D/ViewRootImpl(18401): #1 mView = android.widget.LinearLayout{31c59b V.E...... ......I. 0,0-0,0}
I/InjectionManager(18401): dispatchCreateOptionsMenu :org.jtb.alogcat.LogActivity
I/InjectionManager(18401): dispatchPrepareOptionsMenu :org.jtb.alogcat.LogActivity
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
I/Timeline(18401): Timeline: Activity_idle id: android.os.BinderProxy@12f8d9e time:2676206
D/ViewRootImpl(18401): #3 mView = null
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
I/InjectionManager(18401): dispatchPrepareOptionsMenu :org.jtb.alogcat.LogActivity
D/AbsListView(18401): Get MotionRecognitionManager
D/ViewRootImpl(18401): #1 mView = android.widget.PopupWindow$PopupDecorView{d8e4774 V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
I/InjectionManager(18401): dispatchOptionsItemSelected :org.jtb.alogcat.LogActivity
D/ViewRootImpl(18401): #3 mView = null
D/ViewRootImpl(18401): #1 mView = android.widget.LinearLayout{47cfb4b V.E...... ......I. 0,0-0,0}
E/ViewRootImpl(18401): sendUserActionEvent() mView == null
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl(18401): #3 mView = null
D/ViewRootImpl(18401): #1 mView = android.widget.LinearLayout{87387a5 V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
I/Timeline(18401): Timeline: Activity_idle id: android.os.BinderProxy@12f8d9e time:2722292
D/ViewRootImpl(18401): #3 mView = null
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
I/InjectionManager(18401): dispatchPrepareOptionsMenu :org.jtb.alogcat.LogActivity
D/AbsListView(18401): Get MotionRecognitionManager
D/ViewRootImpl(18401): #1 mView = android.widget.PopupWindow$PopupDecorView{2c46b0b V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
I/InjectionManager(18401): dispatchOptionsItemSelected :org.jtb.alogcat.LogActivity
D/ViewRootImpl(18401): #3 mView = null
W/InputEventReceiver(18401): Attempted to finish an input event but the input event receiver has already been disposed.
E/ViewRootImpl(18401): sendUserActionEvent() mView == null
--------- beginning of system
V/ActivityThread(18401): updateVisibility : ActivityRecord{a5f626e token=android.os.BinderProxy@12f8d9e {org.jtb.alogcat/org.jtb.alogcat.LogActivity}} show : true
V/ActivityThread(18401): updateVisibility : ActivityRecord{a5f626e token=android.os.BinderProxy@12f8d9e {org.jtb.alogcat/org.jtb.alogcat.LogActivity}} show : false
D/ViewRootImpl(18401): #1 mView = android.widget.LinearLayout{7d8e6c4 V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 96 - 0, 1128) vi=Rect(0, 96 - 0, 1128) or=1
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
I/Timeline(18401): Timeline: Activity_idle id: android.os.BinderProxy@12f8d9e time:2746304
D/ViewRootImpl(18401): MSG_RESIZED: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1
D/ViewRootImpl(18401): #3 mView = null
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
I/InjectionManager(18401): dispatchOptionsItemSelected :org.jtb.alogcat.LogActivity
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
I/InjectionManager(18401): dispatchOptionsItemSelected :org.jtb.alogcat.LogActivity
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
I/InjectionManager(18401): dispatchPrepareOptionsMenu :org.jtb.alogcat.LogActivity
D/AbsListView(18401): Get MotionRecognitionManager
D/ViewRootImpl(18401): #1 mView = android.widget.PopupWindow$PopupDecorView{a713a89 V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
I/InjectionManager(18401): dispatchOptionsItemSelected :org.jtb.alogcat.LogActivity
D/ViewRootImpl(18401): #3 mView = null
W/InputEventReceiver(18401): Attempted to finish an input event but the input event receiver has already been disposed.
D/ViewRootImpl(18401): #1 mView = android.widget.LinearLayout{4f2ccbb V.E...... ......I. 0,0-0,0}
E/ViewRootImpl(18401): sendUserActionEvent() mView == null
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl(18401): #3 mView = null
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
V/ActivityThread(18401): updateVisibility : ActivityRecord{a5f626e token=android.os.BinderProxy@12f8d9e {org.jtb.alogcat/org.jtb.alogcat.LogActivity}} show : false
D/ViewRootImpl(18401): #1 mView = android.widget.LinearLayout{4af7423 V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
I/Timeline(18401): Timeline: Activity_idle id: android.os.BinderProxy@12f8d9e time:2801340
D/ViewRootImpl(18401): #3 mView = null
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
I/InjectionManager(18401): dispatchOptionsItemSelected :org.jtb.alogcat.LogActivity
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
I/InjectionManager(18401): dispatchPrepareOptionsMenu :org.jtb.alogcat.LogActivity
D/AbsListView(18401): Get MotionRecognitionManager
D/ViewRootImpl(18401): #1 mView = android.widget.PopupWindow$PopupDecorView{6a1dfe V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
I/InjectionManager(18401): dispatchOptionsItemSelected :org.jtb.alogcat.LogActivity
D/ViewRootImpl(18401): #3 mView = null
D/ViewRootImpl(18401): #1 mView = android.widget.LinearLayout{5a59bba V.E...... ......I. 0,0-0,0}
E/ViewRootImpl(18401): sendUserActionEvent() mView == null
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl(18401): #3 mView = null
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
I/InjectionManager(18401): dispatchPrepareOptionsMenu :org.jtb.alogcat.LogActivity
D/AbsListView(18401): Get MotionRecognitionManager
D/ViewRootImpl(18401): #1 mView = android.widget.PopupWindow$PopupDecorView{97c783c V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
I/InjectionManager(18401): dispatchOptionsItemSelected :org.jtb.alogcat.LogActivity
D/ViewRootImpl(18401): #3 mView = null
W/InputEventReceiver(18401): Attempted to finish an input event but the input event receiver has already been disposed.
D/ViewRootImpl(18401): #1 mView = android.widget.LinearLayout{4c95904 V.E...... ......I. 0,0-0,0}
E/ViewRootImpl(18401): sendUserActionEvent() mView == null
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl(18401): #3 mView = null
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
I/InjectionManager(18401): dispatchOptionsItemSelected :org.jtb.alogcat.LogActivity
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
I/InjectionManager(18401): dispatchOptionsItemSelected :org.jtb.alogcat.LogActivity
V/ActivityThread(18401): updateVisibility : ActivityRecord{a5f626e token=android.os.BinderProxy@12f8d9e {org.jtb.alogcat/org.jtb.alogcat.LogActivity}} show : false
D/ViewRootImpl(18401): #1 mView = android.widget.LinearLayout{f5841b V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
I/Timeline(18401): Timeline: Activity_idle id: android.os.BinderProxy@12f8d9e time:2840325
D/ViewRootImpl(18401): #3 mView = null
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 0
D/ViewRootImpl(18401): ViewPostImeInputStage processPointer 1
I/InjectionManager(18401): dispatchPrepareOptionsMenu :org.jtb.alogcat.LogActivity
D/AbsListView(18401): Get MotionRecognitionManager
D/ViewRootImpl(18401): #1 mView = android.widget.PopupWindow$PopupDecorView{3999456 V.E...... ......I. 0,0-0,0}
D/ViewRootImpl(18401): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1

**Comment by Bra1nK** [comment] 2016-12-09 15:39
I tried again. I closed the app, launched logcat, started the app then back to logcat and posted the log here

**Comment by dc297** [comment] 2016-12-09 15:40
can you add a filter as dc297 or mqttclpro in the logcat app. so that only the logcat related to the application is printed.

**Comment by Bra1nK** [comment] 2016-12-09 15:52
I get nothing in the 'main' log using either of those filters but in 'events' I get 
[0,Filter (dc297)]
[0,Filter (dc297)]
[0,Filter (dc297)]
or
[0,Filter (mqttclpro)]
[0,Filter (mqttclpro)]
 depending which filter I use

**Comment by dc297** [comment] 2016-12-09 16:01
Something should come in the main log. Try killing the app and launching again.

**Comment by Bra1nK** [comment] 2016-12-09 16:07
I've done that a number of times also tried clearing data and even uninstalling then reinstalling but still nothing in the log for 'main' with those filter settings

**Comment by dc297** [comment] 2016-12-09 16:11
Which app are you using for logcat? Let me try that on my phone.

**Comment by Bra1nK** [comment] 2016-12-09 16:14
aLogcat (free) as the other one linked to on the url you posted said something about needing root access

**Comment by dc297** [comment] 2016-12-09 16:39
Even I am not able to get logcat from alogcat. Can you try adb logcat -s mqttclpro from your pc?
And please also share the details of your broker.

**Comment by Bra1nK** [comment] 2016-12-09 17:29
All I get is
adb logcat -s mqttclpro
--------- beginning of main
--------- beginning of system
12-09 17:15:59.724 30733 30733 I mqttclpro: starting service

My Broker is Mosquitto on a Rasberrypi V2 and as I said earlier your MQTT Client works perfectly with it but I'd like to integrate with Tasker hence the plugin

**Comment by cale250** [comment] 2016-12-10 02:36
I'm having the same issue and would like to use your Tasker plugin - same output. Hit me up via PM on FreeNode (same username) and we can try some other things out in real time.

**Comment by cale250** [comment] 2016-12-10 03:51
I just downloaded the source and compiled, played with it a bit and found it worked if I replaced the default values in defineConnectionToBroker. I think the issue may be updating the connection string or information that is being passed to the Paho MQTT client.

**Comment by dc297** [comment] 2016-12-12 11:52
It is possible that the connection to the default broker might be timing out.

**Comment by dc297** [comment] 2016-12-14 00:18
Hi

Published an update. Please check if the issue is fixed after the update.

**Comment by Bra1nK** [comment] 2016-12-14 08:42
That's fixed it, working perfectly now, thanks for you efforts and the change of (lack of ?) icon means I can now distinguish between the plugin and the standard client on my phone. 

What was the issue ?

**Comment by dc297** [comment] 2016-12-15 09:50
The connection to the default broker was timing out and the timeout period was very large. And you might have been changing the broker url in settings while a previous connection attempt was already being made. That must have been causing the issue. Now after removing the default broker details no connection attempt is being made to any server. So when you set your broker details, a fresh connection request is sent.

**Comment by dc297** [comment] 2016-12-15 09:51
you may check the changes in code in the last commit to know more. I'll be closing this issue now. @Bra1nK @cale250 Thanx for your help.

**Closed** 2016-12-15 09:51 UTC
