### ISSUE TITLE
Repeated crashes Android Pie

### ISSUE THREAD

**Issue by tarcus69** [dc297/mqttclpro#73] opened 2019-01-14 12:42 UTC
I've got a Pixel 3 XL, on this, the MQTT client does not work reliably at all, with the following problems:

- When opening the app, the screen is drawn, ads appear, then disappear, then the app crashes. I have submitted a few "feedback" reports with the log included for this from the resulting dialogue. This is repeatable. If the crash doesn't happen then it happens when I click on a broker.
- The "notification" option does not activate any notification, in fact just results in another crash as above, I have submitted "feedback" with log for this too.
- When trying to send an MQTT message (QOS 1), the first attempt always fails, the second attempt and subsequent attempts work. Once the device has been left for a while, this cycle repeats. This happens despite the battery optimisation being disabled for the app.

Has this app been updated for android 9?

**Comment by tarcus69** [comment] 2019-01-14 12:44
Hmm it seems the developer hasn't been responding to any messages for the last 5 months or so, that's a shame, it seemed to be the closest to a working MQTT/Tasker solution that I've found so far.

**Comment by deepessh** [comment] 2019-01-14 14:08
Hey, I'll take a look into this. Is it possible for you to share the logcat here?

**Comment by tarcus69** [comment] 2019-01-14 14:15
Ah excellent, you are still active, that's a relief ;-)

I've scrubbed the app from the phone, reinstalled it, still wasn't working, deleted all the storage and cache, reinstalled it again, and I now at least have the notification active. I didn't think this would work because I recently upgraded my phone and was having these problems on the previous one (Pixel XL on Pie), it seems whatever it didn't like was transferred over when the upgrade to the new phone happened.

The other crashes are still present, I'll sort out some means of getting the logs off later today (I have a business trip to do now), I take it the "feedback" option including logs was of no use to you?

**Comment by niecore** [comment] 2019-01-15 17:31
I am also having problems:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
	at jp.b(:com.google.android.gms.dynamite_adsdynamite@14799081@14.7.99 (100400-223214910):3)
	at jo.a(:com.google.android.gms.dynamite_adsdynamite@14799081@14.7.99 (100400-223214910):3)
	at jq.a(:com.google.android.gms.dynamite_adsdynamite@14799081@14.7.99 (100400-223214910):19)
	at com.google.android.gms.ads.internal.util.aq.a(:com.google.android.gms.dynamite_adsdynamite@14799081@14.7.99 (100400-223214910):15)
	at iu.a(:com.google.android.gms.dynamite_adsdynamite@14799081@14.7.99 (100400-223214910):19)
	at iu.run(:com.google.android.gms.dynamite_adsdynamite@14799081@14.7.99 (100400-223214910):8)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/0000001e/AdsDynamite.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/0000001e/AdsDynamite.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at ad.loadClass(:com.google.android.gms.dynamite_dynamiteloader@14799081@14.7.99 (100400-223214910):4)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 6 more

```

**Comment by deepessh** [comment] 2019-01-16 20:39
Thanks a lot. I'll fix this issue in the next update.

**Comment by niecore** [comment] 2019-01-16 21:22
Let me know, whenever you need more logs or similiar.

**Comment by deepessh** [comment] 2019-01-16 22:11
Apparently, this is a bug on Google Play Services side. There is a workaround available. I have applied that and am pushing the new update to google play. Let me know if the issue is fixed after the version 4.5.1.

Thanks

**Comment by tarcus69** [comment] 2019-01-17 07:32
The crashes on mine have been fixed after the upgrade, so it looks like you've done it. 
Sorry I haven't responded myself previously, I've been extremely busy the last few days so once that's over I'll see if my other issues are gone too.

**Comment by deepessh** [comment] 2019-01-29 19:54
Closing as fixed.

**Closed as completed** 2019-01-29 19:54 UTC
