### ISSUE TITLE
Background Task Crashes

### ISSUE THREAD

**Issue by brianmay** [dc297/mqttclpro#31] opened 2017-10-14 07:14 UTC
Hello,

The background task currently seems repeated crash, and won't stay running. As such any attempt to send outgoing messages from tasker fails.

The foreground process seems to work, although I can see crash messages *after* sending a message.

I first noticed this problem today.

Any ideas?

**Comment by dc297** [comment] 2017-10-14 09:33
Hey Hi

Sorry, my bad. It must have happened after the last update. I added to support for applications other than tasker. But forgot to add backward compatibility for events/actions created before this update. I am working on this right now. Should be fixed in the next few hours.

Cheers

**Comment by dc297** [comment] 2017-10-14 09:54
I have pushed the update to play store.

**Comment by brianmay** [comment] 2017-10-14 10:04
So fast? Thanks! The update hasn't reached my phone yet, but will test it as soon as possible.

**Comment by brianmay** [comment] 2017-10-14 10:20
Finally convinced Google Play to install the update. So far, it looks good. Thanks.

**Comment by brianmay** [comment] 2017-10-14 10:29
It would appear that received messages are not getting passed on to tasker. Out of time now, however will do more testing tomorrow.

**Comment by stipe76** [comment] 2017-10-14 11:13
I am experiencing the same thing. Tasker no longer receives and topic updates.

**Comment by dc297** [comment] 2017-10-14 14:19
Hey @brianmay @stipe76 

I just installed an older version of the app. Created an event and an action in tasker. Testes id. Then upgraded to the latest version. Tested it again. It's working fine for me. 
Please tell me which version of the app you are on and what exactly are you trying to do.

Cheers!
Deepesh

**Comment by brianmay** [comment] 2017-10-14 22:50
I have a simple task that calls the "say test" action when a message is received. This was working perfectly before. Now, mqttclpro will log the message, but there is no evidence that tasker sees it.

**Comment by stipe76** [comment] 2017-10-14 22:53
Brian, I had the same issue. In your event configuration, make sure your varmqtttopic is not null. Adding a value in there solved the issue for me

**Comment by brianmay** [comment] 2017-10-14 23:04
@stipe76: Yes, that helps. Thanks.

**Comment by stipe76** [comment] 2017-10-14 23:05
That was the dev's idea, I was stumped otherwise

**Comment by dc297** [comment] 2017-10-15 07:06
Hey @stipe76 @brianmay 

I'll add a validation which does not allow null topic and message vars. This should fix the issue.

Cheers!
Deepesh

**Comment by stipe76** [comment] 2017-10-19 01:06
Thanks!

**Comment by dc297** [comment] 2017-10-24 07:27
Pushed an update to play store just now. Should be available in a few hours.
Let me know if the issue is fixed.

**Closed** 2017-10-26 19:47 UTC
