### ISSUE TITLE
Macrodroid cannot create action

### ISSUE THREAD

**Issue by mcspr** [dc297/mqttclpro#30] opened 2017-10-12 14:45 UTC
When setting up this plugin as **Tasker/Locale plugin** action [MacroDroid](https://play.google.com/store/apps/details?id=com.arlosoft.macrodroid) shows this toast

>  Extra **com.twofortyfouram.locale.intent.extra.BUNDLE** is required. To resolve this issue, put the bundle extra in the Activity result intent

right after trying to save it, and this in the log: 
```
10-12 17:26:50.234  7590  8272 V Lumberjack: Loaded plug-in map in 37 milliseconds
10-12 17:26:50.238  5719 10779 I ActivityManager: START u0 {act=com.twofortyfouram.locale.intent.action.EDIT_SETTING cmp=in.dc297.mqttclpro/.tasker.ActionEditActivity (has extras)} from uid 10269 on display 0
10-12 17:26:53.568  7590  7590 I Lumberjack: Received result code RESULT_OK
10-12 17:26:53.573  7590  7590 V Lumberjack: Encountered errors: [BUNDLE_MISSING]
```

Looking at the code, it contains many commented out sections processing that bundle. Why is that?

Also, this should probably be prefixed with `com.twofortyfouram.locale`, not `in.dc297.mqttclpro.tasker`:
https://github.com/dc297/mqttclpro/blob/8554cf11c569096d87ca6fc09ccb8dd079f1eaa7/app/src/main/java/in/dc297/mqttclpro/tasker/Intent.java#L190

**Comment by dc297** [comment] 2017-10-12 21:26
Hey thanx for raising the issue. This has been bugging me for quite some time.

I have been able to get publish action working with Macrodroid. 
However Macrodroid doesn't support hostSupportsRequestQueryDataPassThrough. Due to this I am not able to get the trigger plugin working with Macrodroid. I am still looking for ways to pass published message to my query receiver so that I can compare configured and published message details if they match or not.

Let me know if you have any ideas.

Cheers!
Deepesh

**Comment by mcspr** [comment] 2017-10-13 05:11
Oh, I've totally forgot about the events. But that data pass-through thing is tasker specific feature. Variables are too.

Did you try just comparing topic+message (from the aforementioned bundle, inside the intent to the QueryReceiver) with some internal cache? That would would also cover the case when plugin host (locale, macrodroid, tasker etc.) sends the query action all by itself.

**Comment by dc297** [comment] 2017-10-13 23:22
Hi

This should be available in the latest version. Do check it out and let me know your observations. However, variable replacement is not supported. So, the condition is satisfied if the topics match.

Cheers!
Deepesh

**Comment by mcspr** [comment] 2017-10-15 01:12
Great! Thanks! Actions now work fine.

But event cannot be configured with empty *varmessage* and *varmqtttopic*

**Comment by dc297** [comment] 2017-10-15 07:28
Yeah...identified that issue. Will be fixed in the next version.

**Comment by mcspr** [comment] 2017-10-19 01:16
Btw any thoughts about topic/message value checks in the trigger itself?

**Comment by dc297** [comment] 2017-10-19 06:43
I have fixed the issue. Let me push an update tonight.

**Comment by dc297** [comment] 2017-10-24 07:27
Pushed an update to play store just now. Should be available in a few hours.
Let me know if the issue is fixed.

**Closed** 2017-10-26 19:47 UTC

**Comment by dc297** [comment] 2017-10-27 13:31
Hey, sorry, unable to understand what you are suggesting. Could you share more details or, maybe, an example?

**Comment by mcspr** [comment] 2017-10-27 15:05
I've remembered something. Issue #2 (already descibes what i mean :)
Tasker already does all matching, comparing etc. https://github.com/dc297/mqttclpro/issues/2#issuecomment-273922577
> tasker already supports pattern matching. So implementing pattern matching in the app would be redundant.

An example would be array of sensors. Each sensor sends numeric value to the topic - in tasker this could be easily matched with math condition like %msg > 25 or %msg == 0 (for this even string comparsion would do. regex is overkill)

Topic could be matched by the same spec as subscription. Paho checker (*topicFilter* from user, *topicName* from the event): 
https://github.com/eclipse/paho.mqtt.java/blob/75594f0b226b14911f397b69059c18a50eaabb54/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/MqttTopic.java#L248

**Comment by dc297** [comment] 2017-10-27 20:06
Hey, I have pushed a new update on the beta channel. In the new version, you can compare message and topic. Do check it out.

Cheers!

**Comment by mcspr** [comment] 2017-11-07 21:41
Sorry about not answering earlier:) Ran the matcher for about a week with couple different matchers, everything seems fine.

Setting both variables when creating action is still a must. Maybe they should just be what hint says by default? `varmessage` (or `varmqttmsg`) / `varmqtttopic`
